DROP TABLE IF EXISTS parent;
DROP TABLE IF EXISTS child;


CREATE TABLE parent(
	parent_id INTEGER PRIMARY KEY AUTOINCREMENT,
	parent_username TEXT UNIQUE NOT NULL,
	parent_email TEXT UNIQUE NOT NULL,
	parent_password TEXT NOT NULL
);

CREATE TABLE child(
	child_id INTEGER PRIMARY KEY AUTOINCREMENT,
	child_username TEXT UNIQUE NOT NULL,
	parent_email TEXT UNIQUE NOT NULL,
	child_password TEXT NOT NULL
);
